// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

public interface CourseItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CourseItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string course_id = 1;</code>
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();

  /**
   * <code>string course_day_of_week = 2;</code>
   */
  java.lang.String getCourseDayOfWeek();
  /**
   * <code>string course_day_of_week = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseDayOfWeekBytes();
}
