// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

public final class CourseSchedulingServiceImpl {
  private CourseSchedulingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCourseScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCourseScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCourseScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCourseScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCourseScheduleByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCourseScheduleByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCourseScheduleByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCourseScheduleByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllCoursesScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllCoursesScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllCoursesScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllCoursesScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CourseItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CourseItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014course.proto\"I\n\030AddCourseScheduleReque" +
      "st\022\021\n\tcourse_id\030\001 \001(\t\022\032\n\022course_day_of_w" +
      "eek\030\002 \003(\t\"<\n\031AddCourseScheduleResponse\022\016" +
      "\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"1\n\034GetCo" +
      "urseScheduleByIdRequest\022\021\n\tcourse_id\030\001 \001" +
      "(\t\"N\n\035GetCourseScheduleByIdResponse\022\021\n\tc" +
      "ourse_id\030\001 \001(\t\022\032\n\022course_day_of_week\030\002 \003" +
      "(\t\"1\n\034GetAllCoursesScheduleRequest\022\021\n\tco" +
      "urse_id\030\001 \001(\t\"A\n\035GetAllCoursesScheduleRe" +
      "sponse\022 \n\013course_item\030\001 \003(\0132\013.CourseItem" +
      "\";\n\nCourseItem\022\021\n\tcourse_id\030\001 \001(\t\022\032\n\022cou" +
      "rse_day_of_week\030\002 \001(\t2\370\001\n\020CourseManageme" +
      "nt\022B\n\tAddCourse\022\031.AddCourseScheduleReque" +
      "st\032\032.AddCourseScheduleResponse\022N\n\rGetCou" +
      "rseById\022\035.GetCourseScheduleByIdRequest\032\036" +
      ".GetCourseScheduleByIdResponse\022P\n\rGetAll" +
      "Courses\022\035.GetAllCoursesScheduleRequest\032\036" +
      ".GetAllCoursesScheduleResponse0\001B5\n\024edu." +
      "courseSchedulingB\033CourseSchedulingServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AddCourseScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddCourseScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCourseScheduleRequest_descriptor,
        new java.lang.String[] { "CourseId", "CourseDayOfWeek", });
    internal_static_AddCourseScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddCourseScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCourseScheduleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_GetCourseScheduleByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetCourseScheduleByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCourseScheduleByIdRequest_descriptor,
        new java.lang.String[] { "CourseId", });
    internal_static_GetCourseScheduleByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetCourseScheduleByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCourseScheduleByIdResponse_descriptor,
        new java.lang.String[] { "CourseId", "CourseDayOfWeek", });
    internal_static_GetAllCoursesScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetAllCoursesScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllCoursesScheduleRequest_descriptor,
        new java.lang.String[] { "CourseId", });
    internal_static_GetAllCoursesScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetAllCoursesScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllCoursesScheduleResponse_descriptor,
        new java.lang.String[] { "CourseItem", });
    internal_static_CourseItem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CourseItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CourseItem_descriptor,
        new java.lang.String[] { "CourseId", "CourseDayOfWeek", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
