// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

/**
 * Protobuf type {@code GetAllCoursesScheduleResponse}
 */
public  final class GetAllCoursesScheduleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAllCoursesScheduleResponse)
    GetAllCoursesScheduleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllCoursesScheduleResponse.newBuilder() to construct.
  private GetAllCoursesScheduleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllCoursesScheduleResponse() {
    courseItem_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllCoursesScheduleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              courseItem_ = new java.util.ArrayList<edu.courseScheduling.CourseItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            courseItem_.add(
                input.readMessage(edu.courseScheduling.CourseItem.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        courseItem_ = java.util.Collections.unmodifiableList(courseItem_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetAllCoursesScheduleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetAllCoursesScheduleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.courseScheduling.GetAllCoursesScheduleResponse.class, edu.courseScheduling.GetAllCoursesScheduleResponse.Builder.class);
  }

  public static final int COURSE_ITEM_FIELD_NUMBER = 1;
  private java.util.List<edu.courseScheduling.CourseItem> courseItem_;
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  public java.util.List<edu.courseScheduling.CourseItem> getCourseItemList() {
    return courseItem_;
  }
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  public java.util.List<? extends edu.courseScheduling.CourseItemOrBuilder> 
      getCourseItemOrBuilderList() {
    return courseItem_;
  }
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  public int getCourseItemCount() {
    return courseItem_.size();
  }
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  public edu.courseScheduling.CourseItem getCourseItem(int index) {
    return courseItem_.get(index);
  }
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  public edu.courseScheduling.CourseItemOrBuilder getCourseItemOrBuilder(
      int index) {
    return courseItem_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < courseItem_.size(); i++) {
      output.writeMessage(1, courseItem_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < courseItem_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, courseItem_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.courseScheduling.GetAllCoursesScheduleResponse)) {
      return super.equals(obj);
    }
    edu.courseScheduling.GetAllCoursesScheduleResponse other = (edu.courseScheduling.GetAllCoursesScheduleResponse) obj;

    boolean result = true;
    result = result && getCourseItemList()
        .equals(other.getCourseItemList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCourseItemCount() > 0) {
      hash = (37 * hash) + COURSE_ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getCourseItemList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.courseScheduling.GetAllCoursesScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.courseScheduling.GetAllCoursesScheduleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllCoursesScheduleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllCoursesScheduleResponse)
      edu.courseScheduling.GetAllCoursesScheduleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetAllCoursesScheduleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetAllCoursesScheduleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.courseScheduling.GetAllCoursesScheduleResponse.class, edu.courseScheduling.GetAllCoursesScheduleResponse.Builder.class);
    }

    // Construct using edu.courseScheduling.GetAllCoursesScheduleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCourseItemFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (courseItemBuilder_ == null) {
        courseItem_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        courseItemBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetAllCoursesScheduleResponse_descriptor;
    }

    @java.lang.Override
    public edu.courseScheduling.GetAllCoursesScheduleResponse getDefaultInstanceForType() {
      return edu.courseScheduling.GetAllCoursesScheduleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public edu.courseScheduling.GetAllCoursesScheduleResponse build() {
      edu.courseScheduling.GetAllCoursesScheduleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.courseScheduling.GetAllCoursesScheduleResponse buildPartial() {
      edu.courseScheduling.GetAllCoursesScheduleResponse result = new edu.courseScheduling.GetAllCoursesScheduleResponse(this);
      int from_bitField0_ = bitField0_;
      if (courseItemBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          courseItem_ = java.util.Collections.unmodifiableList(courseItem_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.courseItem_ = courseItem_;
      } else {
        result.courseItem_ = courseItemBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.courseScheduling.GetAllCoursesScheduleResponse) {
        return mergeFrom((edu.courseScheduling.GetAllCoursesScheduleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.courseScheduling.GetAllCoursesScheduleResponse other) {
      if (other == edu.courseScheduling.GetAllCoursesScheduleResponse.getDefaultInstance()) return this;
      if (courseItemBuilder_ == null) {
        if (!other.courseItem_.isEmpty()) {
          if (courseItem_.isEmpty()) {
            courseItem_ = other.courseItem_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCourseItemIsMutable();
            courseItem_.addAll(other.courseItem_);
          }
          onChanged();
        }
      } else {
        if (!other.courseItem_.isEmpty()) {
          if (courseItemBuilder_.isEmpty()) {
            courseItemBuilder_.dispose();
            courseItemBuilder_ = null;
            courseItem_ = other.courseItem_;
            bitField0_ = (bitField0_ & ~0x00000001);
            courseItemBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCourseItemFieldBuilder() : null;
          } else {
            courseItemBuilder_.addAllMessages(other.courseItem_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.courseScheduling.GetAllCoursesScheduleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.courseScheduling.GetAllCoursesScheduleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<edu.courseScheduling.CourseItem> courseItem_ =
      java.util.Collections.emptyList();
    private void ensureCourseItemIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        courseItem_ = new java.util.ArrayList<edu.courseScheduling.CourseItem>(courseItem_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.courseScheduling.CourseItem, edu.courseScheduling.CourseItem.Builder, edu.courseScheduling.CourseItemOrBuilder> courseItemBuilder_;

    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public java.util.List<edu.courseScheduling.CourseItem> getCourseItemList() {
      if (courseItemBuilder_ == null) {
        return java.util.Collections.unmodifiableList(courseItem_);
      } else {
        return courseItemBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public int getCourseItemCount() {
      if (courseItemBuilder_ == null) {
        return courseItem_.size();
      } else {
        return courseItemBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public edu.courseScheduling.CourseItem getCourseItem(int index) {
      if (courseItemBuilder_ == null) {
        return courseItem_.get(index);
      } else {
        return courseItemBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder setCourseItem(
        int index, edu.courseScheduling.CourseItem value) {
      if (courseItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCourseItemIsMutable();
        courseItem_.set(index, value);
        onChanged();
      } else {
        courseItemBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder setCourseItem(
        int index, edu.courseScheduling.CourseItem.Builder builderForValue) {
      if (courseItemBuilder_ == null) {
        ensureCourseItemIsMutable();
        courseItem_.set(index, builderForValue.build());
        onChanged();
      } else {
        courseItemBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder addCourseItem(edu.courseScheduling.CourseItem value) {
      if (courseItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCourseItemIsMutable();
        courseItem_.add(value);
        onChanged();
      } else {
        courseItemBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder addCourseItem(
        int index, edu.courseScheduling.CourseItem value) {
      if (courseItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCourseItemIsMutable();
        courseItem_.add(index, value);
        onChanged();
      } else {
        courseItemBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder addCourseItem(
        edu.courseScheduling.CourseItem.Builder builderForValue) {
      if (courseItemBuilder_ == null) {
        ensureCourseItemIsMutable();
        courseItem_.add(builderForValue.build());
        onChanged();
      } else {
        courseItemBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder addCourseItem(
        int index, edu.courseScheduling.CourseItem.Builder builderForValue) {
      if (courseItemBuilder_ == null) {
        ensureCourseItemIsMutable();
        courseItem_.add(index, builderForValue.build());
        onChanged();
      } else {
        courseItemBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder addAllCourseItem(
        java.lang.Iterable<? extends edu.courseScheduling.CourseItem> values) {
      if (courseItemBuilder_ == null) {
        ensureCourseItemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, courseItem_);
        onChanged();
      } else {
        courseItemBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder clearCourseItem() {
      if (courseItemBuilder_ == null) {
        courseItem_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        courseItemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public Builder removeCourseItem(int index) {
      if (courseItemBuilder_ == null) {
        ensureCourseItemIsMutable();
        courseItem_.remove(index);
        onChanged();
      } else {
        courseItemBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public edu.courseScheduling.CourseItem.Builder getCourseItemBuilder(
        int index) {
      return getCourseItemFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public edu.courseScheduling.CourseItemOrBuilder getCourseItemOrBuilder(
        int index) {
      if (courseItemBuilder_ == null) {
        return courseItem_.get(index);  } else {
        return courseItemBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public java.util.List<? extends edu.courseScheduling.CourseItemOrBuilder> 
         getCourseItemOrBuilderList() {
      if (courseItemBuilder_ != null) {
        return courseItemBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(courseItem_);
      }
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public edu.courseScheduling.CourseItem.Builder addCourseItemBuilder() {
      return getCourseItemFieldBuilder().addBuilder(
          edu.courseScheduling.CourseItem.getDefaultInstance());
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public edu.courseScheduling.CourseItem.Builder addCourseItemBuilder(
        int index) {
      return getCourseItemFieldBuilder().addBuilder(
          index, edu.courseScheduling.CourseItem.getDefaultInstance());
    }
    /**
     * <code>repeated .CourseItem course_item = 1;</code>
     */
    public java.util.List<edu.courseScheduling.CourseItem.Builder> 
         getCourseItemBuilderList() {
      return getCourseItemFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.courseScheduling.CourseItem, edu.courseScheduling.CourseItem.Builder, edu.courseScheduling.CourseItemOrBuilder> 
        getCourseItemFieldBuilder() {
      if (courseItemBuilder_ == null) {
        courseItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.courseScheduling.CourseItem, edu.courseScheduling.CourseItem.Builder, edu.courseScheduling.CourseItemOrBuilder>(
                courseItem_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        courseItem_ = null;
      }
      return courseItemBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAllCoursesScheduleResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllCoursesScheduleResponse)
  private static final edu.courseScheduling.GetAllCoursesScheduleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.courseScheduling.GetAllCoursesScheduleResponse();
  }

  public static edu.courseScheduling.GetAllCoursesScheduleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllCoursesScheduleResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllCoursesScheduleResponse>() {
    @java.lang.Override
    public GetAllCoursesScheduleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAllCoursesScheduleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllCoursesScheduleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllCoursesScheduleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.courseScheduling.GetAllCoursesScheduleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

