// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

public interface GetAllCoursesScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllCoursesScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional filter to apply when fetching courses based on course name
   * </pre>
   *
   * <code>string course_id = 1;</code>
   */
  java.lang.String getCourseId();
  /**
   * <pre>
   * Optional filter to apply when fetching courses based on course name
   * </pre>
   *
   * <code>string course_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();
}
