// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

public interface GetAllCoursesScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllCoursesScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  java.util.List<edu.courseScheduling.CourseItem> 
      getCourseItemList();
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  edu.courseScheduling.CourseItem getCourseItem(int index);
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  int getCourseItemCount();
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  java.util.List<? extends edu.courseScheduling.CourseItemOrBuilder> 
      getCourseItemOrBuilderList();
  /**
   * <code>repeated .CourseItem course_item = 1;</code>
   */
  edu.courseScheduling.CourseItemOrBuilder getCourseItemOrBuilder(
      int index);
}
