// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

/**
 * Protobuf type {@code GetCourseScheduleByIdResponse}
 */
public  final class GetCourseScheduleByIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetCourseScheduleByIdResponse)
    GetCourseScheduleByIdResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCourseScheduleByIdResponse.newBuilder() to construct.
  private GetCourseScheduleByIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCourseScheduleByIdResponse() {
    courseId_ = "";
    courseDayOfWeek_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetCourseScheduleByIdResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            courseId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              courseDayOfWeek_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            courseDayOfWeek_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        courseDayOfWeek_ = courseDayOfWeek_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetCourseScheduleByIdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetCourseScheduleByIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.courseScheduling.GetCourseScheduleByIdResponse.class, edu.courseScheduling.GetCourseScheduleByIdResponse.Builder.class);
  }

  private int bitField0_;
  public static final int COURSE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object courseId_;
  /**
   * <code>string course_id = 1;</code>
   */
  public java.lang.String getCourseId() {
    java.lang.Object ref = courseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      courseId_ = s;
      return s;
    }
  }
  /**
   * <code>string course_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCourseIdBytes() {
    java.lang.Object ref = courseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      courseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COURSE_DAY_OF_WEEK_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList courseDayOfWeek_;
  /**
   * <code>repeated string course_day_of_week = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCourseDayOfWeekList() {
    return courseDayOfWeek_;
  }
  /**
   * <code>repeated string course_day_of_week = 2;</code>
   */
  public int getCourseDayOfWeekCount() {
    return courseDayOfWeek_.size();
  }
  /**
   * <code>repeated string course_day_of_week = 2;</code>
   */
  public java.lang.String getCourseDayOfWeek(int index) {
    return courseDayOfWeek_.get(index);
  }
  /**
   * <code>repeated string course_day_of_week = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCourseDayOfWeekBytes(int index) {
    return courseDayOfWeek_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCourseIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, courseId_);
    }
    for (int i = 0; i < courseDayOfWeek_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, courseDayOfWeek_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCourseIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, courseId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < courseDayOfWeek_.size(); i++) {
        dataSize += computeStringSizeNoTag(courseDayOfWeek_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCourseDayOfWeekList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.courseScheduling.GetCourseScheduleByIdResponse)) {
      return super.equals(obj);
    }
    edu.courseScheduling.GetCourseScheduleByIdResponse other = (edu.courseScheduling.GetCourseScheduleByIdResponse) obj;

    boolean result = true;
    result = result && getCourseId()
        .equals(other.getCourseId());
    result = result && getCourseDayOfWeekList()
        .equals(other.getCourseDayOfWeekList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COURSE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCourseId().hashCode();
    if (getCourseDayOfWeekCount() > 0) {
      hash = (37 * hash) + COURSE_DAY_OF_WEEK_FIELD_NUMBER;
      hash = (53 * hash) + getCourseDayOfWeekList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.courseScheduling.GetCourseScheduleByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.courseScheduling.GetCourseScheduleByIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetCourseScheduleByIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetCourseScheduleByIdResponse)
      edu.courseScheduling.GetCourseScheduleByIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetCourseScheduleByIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetCourseScheduleByIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.courseScheduling.GetCourseScheduleByIdResponse.class, edu.courseScheduling.GetCourseScheduleByIdResponse.Builder.class);
    }

    // Construct using edu.courseScheduling.GetCourseScheduleByIdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      courseId_ = "";

      courseDayOfWeek_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.courseScheduling.CourseSchedulingServiceImpl.internal_static_GetCourseScheduleByIdResponse_descriptor;
    }

    @java.lang.Override
    public edu.courseScheduling.GetCourseScheduleByIdResponse getDefaultInstanceForType() {
      return edu.courseScheduling.GetCourseScheduleByIdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public edu.courseScheduling.GetCourseScheduleByIdResponse build() {
      edu.courseScheduling.GetCourseScheduleByIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.courseScheduling.GetCourseScheduleByIdResponse buildPartial() {
      edu.courseScheduling.GetCourseScheduleByIdResponse result = new edu.courseScheduling.GetCourseScheduleByIdResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.courseId_ = courseId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        courseDayOfWeek_ = courseDayOfWeek_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.courseDayOfWeek_ = courseDayOfWeek_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.courseScheduling.GetCourseScheduleByIdResponse) {
        return mergeFrom((edu.courseScheduling.GetCourseScheduleByIdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.courseScheduling.GetCourseScheduleByIdResponse other) {
      if (other == edu.courseScheduling.GetCourseScheduleByIdResponse.getDefaultInstance()) return this;
      if (!other.getCourseId().isEmpty()) {
        courseId_ = other.courseId_;
        onChanged();
      }
      if (!other.courseDayOfWeek_.isEmpty()) {
        if (courseDayOfWeek_.isEmpty()) {
          courseDayOfWeek_ = other.courseDayOfWeek_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCourseDayOfWeekIsMutable();
          courseDayOfWeek_.addAll(other.courseDayOfWeek_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.courseScheduling.GetCourseScheduleByIdResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.courseScheduling.GetCourseScheduleByIdResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object courseId_ = "";
    /**
     * <code>string course_id = 1;</code>
     */
    public java.lang.String getCourseId() {
      java.lang.Object ref = courseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCourseIdBytes() {
      java.lang.Object ref = courseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public Builder setCourseId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      courseId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public Builder clearCourseId() {
      
      courseId_ = getDefaultInstance().getCourseId();
      onChanged();
      return this;
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public Builder setCourseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      courseId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList courseDayOfWeek_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCourseDayOfWeekIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        courseDayOfWeek_ = new com.google.protobuf.LazyStringArrayList(courseDayOfWeek_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCourseDayOfWeekList() {
      return courseDayOfWeek_.getUnmodifiableView();
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public int getCourseDayOfWeekCount() {
      return courseDayOfWeek_.size();
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public java.lang.String getCourseDayOfWeek(int index) {
      return courseDayOfWeek_.get(index);
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCourseDayOfWeekBytes(int index) {
      return courseDayOfWeek_.getByteString(index);
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public Builder setCourseDayOfWeek(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseDayOfWeekIsMutable();
      courseDayOfWeek_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public Builder addCourseDayOfWeek(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseDayOfWeekIsMutable();
      courseDayOfWeek_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public Builder addAllCourseDayOfWeek(
        java.lang.Iterable<java.lang.String> values) {
      ensureCourseDayOfWeekIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, courseDayOfWeek_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public Builder clearCourseDayOfWeek() {
      courseDayOfWeek_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_day_of_week = 2;</code>
     */
    public Builder addCourseDayOfWeekBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCourseDayOfWeekIsMutable();
      courseDayOfWeek_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetCourseScheduleByIdResponse)
  }

  // @@protoc_insertion_point(class_scope:GetCourseScheduleByIdResponse)
  private static final edu.courseScheduling.GetCourseScheduleByIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.courseScheduling.GetCourseScheduleByIdResponse();
  }

  public static edu.courseScheduling.GetCourseScheduleByIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCourseScheduleByIdResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCourseScheduleByIdResponse>() {
    @java.lang.Override
    public GetCourseScheduleByIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetCourseScheduleByIdResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetCourseScheduleByIdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCourseScheduleByIdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.courseScheduling.GetCourseScheduleByIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

