// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course.proto

package edu.courseScheduling;

public interface GetCourseScheduleByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCourseScheduleByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string course_id = 1;</code>
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();
}
