// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package edu.teacherScheduling;

/**
 * Protobuf type {@code GetTeacherScheduleByIdRequest}
 */
public  final class GetTeacherScheduleByIdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetTeacherScheduleByIdRequest)
    GetTeacherScheduleByIdRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTeacherScheduleByIdRequest.newBuilder() to construct.
  private GetTeacherScheduleByIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTeacherScheduleByIdRequest() {
    teacherId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTeacherScheduleByIdRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            teacherId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.teacherScheduling.TeacherSchedulingServiceImpl.internal_static_GetTeacherScheduleByIdRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.teacherScheduling.TeacherSchedulingServiceImpl.internal_static_GetTeacherScheduleByIdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.teacherScheduling.GetTeacherScheduleByIdRequest.class, edu.teacherScheduling.GetTeacherScheduleByIdRequest.Builder.class);
  }

  public static final int TEACHER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object teacherId_;
  /**
   * <code>string teacher_id = 1;</code>
   */
  public java.lang.String getTeacherId() {
    java.lang.Object ref = teacherId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      teacherId_ = s;
      return s;
    }
  }
  /**
   * <code>string teacher_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTeacherIdBytes() {
    java.lang.Object ref = teacherId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      teacherId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTeacherIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, teacherId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTeacherIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, teacherId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.teacherScheduling.GetTeacherScheduleByIdRequest)) {
      return super.equals(obj);
    }
    edu.teacherScheduling.GetTeacherScheduleByIdRequest other = (edu.teacherScheduling.GetTeacherScheduleByIdRequest) obj;

    boolean result = true;
    result = result && getTeacherId()
        .equals(other.getTeacherId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEACHER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTeacherId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.teacherScheduling.GetTeacherScheduleByIdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetTeacherScheduleByIdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetTeacherScheduleByIdRequest)
      edu.teacherScheduling.GetTeacherScheduleByIdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.teacherScheduling.TeacherSchedulingServiceImpl.internal_static_GetTeacherScheduleByIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.teacherScheduling.TeacherSchedulingServiceImpl.internal_static_GetTeacherScheduleByIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.teacherScheduling.GetTeacherScheduleByIdRequest.class, edu.teacherScheduling.GetTeacherScheduleByIdRequest.Builder.class);
    }

    // Construct using edu.teacherScheduling.GetTeacherScheduleByIdRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      teacherId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.teacherScheduling.TeacherSchedulingServiceImpl.internal_static_GetTeacherScheduleByIdRequest_descriptor;
    }

    @java.lang.Override
    public edu.teacherScheduling.GetTeacherScheduleByIdRequest getDefaultInstanceForType() {
      return edu.teacherScheduling.GetTeacherScheduleByIdRequest.getDefaultInstance();
    }

    @java.lang.Override
    public edu.teacherScheduling.GetTeacherScheduleByIdRequest build() {
      edu.teacherScheduling.GetTeacherScheduleByIdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.teacherScheduling.GetTeacherScheduleByIdRequest buildPartial() {
      edu.teacherScheduling.GetTeacherScheduleByIdRequest result = new edu.teacherScheduling.GetTeacherScheduleByIdRequest(this);
      result.teacherId_ = teacherId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.teacherScheduling.GetTeacherScheduleByIdRequest) {
        return mergeFrom((edu.teacherScheduling.GetTeacherScheduleByIdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.teacherScheduling.GetTeacherScheduleByIdRequest other) {
      if (other == edu.teacherScheduling.GetTeacherScheduleByIdRequest.getDefaultInstance()) return this;
      if (!other.getTeacherId().isEmpty()) {
        teacherId_ = other.teacherId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.teacherScheduling.GetTeacherScheduleByIdRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.teacherScheduling.GetTeacherScheduleByIdRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object teacherId_ = "";
    /**
     * <code>string teacher_id = 1;</code>
     */
    public java.lang.String getTeacherId() {
      java.lang.Object ref = teacherId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teacherId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string teacher_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTeacherIdBytes() {
      java.lang.Object ref = teacherId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teacherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string teacher_id = 1;</code>
     */
    public Builder setTeacherId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      teacherId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string teacher_id = 1;</code>
     */
    public Builder clearTeacherId() {
      
      teacherId_ = getDefaultInstance().getTeacherId();
      onChanged();
      return this;
    }
    /**
     * <code>string teacher_id = 1;</code>
     */
    public Builder setTeacherIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      teacherId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetTeacherScheduleByIdRequest)
  }

  // @@protoc_insertion_point(class_scope:GetTeacherScheduleByIdRequest)
  private static final edu.teacherScheduling.GetTeacherScheduleByIdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.teacherScheduling.GetTeacherScheduleByIdRequest();
  }

  public static edu.teacherScheduling.GetTeacherScheduleByIdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTeacherScheduleByIdRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetTeacherScheduleByIdRequest>() {
    @java.lang.Override
    public GetTeacherScheduleByIdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTeacherScheduleByIdRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTeacherScheduleByIdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTeacherScheduleByIdRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.teacherScheduling.GetTeacherScheduleByIdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

