// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package edu.teacherScheduling;

public interface GetTeacherScheduleByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTeacherScheduleByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string teacher_id = 1;</code>
   */
  java.lang.String getTeacherId();
  /**
   * <code>string teacher_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTeacherIdBytes();
}
