// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package edu.teacherScheduling;

public final class TeacherSchedulingServiceImpl {
  private TeacherSchedulingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddTeacherScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddTeacherScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddTeacherScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddTeacherScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTeacherScheduleByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTeacherScheduleByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTeacherScheduleByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTeacherScheduleByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTeacherScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTeacherScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTeacherScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTeacherScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TeachingItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TeachingItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rteacher.proto\"C\n\031AddTeacherScheduleReq" +
      "uest\022\022\n\nteacher_id\030\001 \001(\t\022\022\n\ncourse_ids\030\002" +
      " \003(\t\"=\n\032AddTeacherScheduleResponse\022\016\n\006st" +
      "atus\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"3\n\035GetTeache" +
      "rScheduleByIdRequest\022\022\n\nteacher_id\030\001 \001(\t" +
      "\"H\n\036GetTeacherScheduleByIdResponse\022\022\n\nte" +
      "acher_id\030\001 \001(\t\022\022\n\ncourse_ids\030\002 \003(\t\"F\n\034Up" +
      "dateTeacherScheduleRequest\022\022\n\nteacher_id" +
      "\030\001 \001(\t\022\022\n\ncourse_ids\030\002 \003(\t\"E\n\035UpdateTeac" +
      "herScheduleResponse\022$\n\rteaching_item\030\001 \003" +
      "(\0132\r.TeachingItem\"6\n\014TeachingItem\022\022\n\ntea" +
      "cher_id\030\001 \001(\t\022\022\n\ncourse_ids\030\002 \001(\t2\232\002\n\021Te" +
      "acherManagement\022M\n\022AddTeacherSchedule\022\032." +
      "AddTeacherScheduleRequest\032\033.AddTeacherSc" +
      "heduleResponse\022Y\n\026GetTeacherScheduleById" +
      "\022\036.GetTeacherScheduleByIdRequest\032\037.GetTe" +
      "acherScheduleByIdResponse\022[\n\026UpdateTeach" +
      "erSchedules\022\035.UpdateTeacherScheduleReque" +
      "st\032\036.UpdateTeacherScheduleResponse(\0010\001B7" +
      "\n\025edu.teacherSchedulingB\034TeacherScheduli" +
      "ngServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AddTeacherScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddTeacherScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddTeacherScheduleRequest_descriptor,
        new java.lang.String[] { "TeacherId", "CourseIds", });
    internal_static_AddTeacherScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddTeacherScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddTeacherScheduleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_GetTeacherScheduleByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetTeacherScheduleByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTeacherScheduleByIdRequest_descriptor,
        new java.lang.String[] { "TeacherId", });
    internal_static_GetTeacherScheduleByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetTeacherScheduleByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTeacherScheduleByIdResponse_descriptor,
        new java.lang.String[] { "TeacherId", "CourseIds", });
    internal_static_UpdateTeacherScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UpdateTeacherScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTeacherScheduleRequest_descriptor,
        new java.lang.String[] { "TeacherId", "CourseIds", });
    internal_static_UpdateTeacherScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdateTeacherScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTeacherScheduleResponse_descriptor,
        new java.lang.String[] { "TeachingItem", });
    internal_static_TeachingItem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_TeachingItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TeachingItem_descriptor,
        new java.lang.String[] { "TeacherId", "CourseIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
