// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package edu.teacherScheduling;

public interface TeachingItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TeachingItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string teacher_id = 1;</code>
   */
  java.lang.String getTeacherId();
  /**
   * <code>string teacher_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTeacherIdBytes();

  /**
   * <code>string course_ids = 2;</code>
   */
  java.lang.String getCourseIds();
  /**
   * <code>string course_ids = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdsBytes();
}
