// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package edu.teacherScheduling;

public interface UpdateTeacherScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateTeacherScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TeachingItem teaching_item = 1;</code>
   */
  java.util.List<edu.teacherScheduling.TeachingItem> 
      getTeachingItemList();
  /**
   * <code>repeated .TeachingItem teaching_item = 1;</code>
   */
  edu.teacherScheduling.TeachingItem getTeachingItem(int index);
  /**
   * <code>repeated .TeachingItem teaching_item = 1;</code>
   */
  int getTeachingItemCount();
  /**
   * <code>repeated .TeachingItem teaching_item = 1;</code>
   */
  java.util.List<? extends edu.teacherScheduling.TeachingItemOrBuilder> 
      getTeachingItemOrBuilderList();
  /**
   * <code>repeated .TeachingItem teaching_item = 1;</code>
   */
  edu.teacherScheduling.TeachingItemOrBuilder getTeachingItemOrBuilder(
      int index);
}
