// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduling.proto

package cv.scheduling;

/**
 * Protobuf type {@code scheduling.ResourceAvailabilityResponse}
 */
public  final class ResourceAvailabilityResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scheduling.ResourceAvailabilityResponse)
    ResourceAvailabilityResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceAvailabilityResponse.newBuilder() to construct.
  private ResourceAvailabilityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceAvailabilityResponse() {
    resourceId_ = "";
    availableTimes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceAvailabilityResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            resourceId_ = s;
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              availableTimes_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000002;
            }
            availableTimes_.add(input.readInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              availableTimes_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              availableTimes_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        availableTimes_ = java.util.Collections.unmodifiableList(availableTimes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_ResourceAvailabilityResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_ResourceAvailabilityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cv.scheduling.ResourceAvailabilityResponse.class, cv.scheduling.ResourceAvailabilityResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object resourceId_;
  /**
   * <code>string resource_id = 1;</code>
   */
  public java.lang.String getResourceId() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceId_ = s;
      return s;
    }
  }
  /**
   * <code>string resource_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResourceIdBytes() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLE_TIMES_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Long> availableTimes_;
  /**
   * <code>repeated int64 available_times = 2;</code>
   */
  public java.util.List<java.lang.Long>
      getAvailableTimesList() {
    return availableTimes_;
  }
  /**
   * <code>repeated int64 available_times = 2;</code>
   */
  public int getAvailableTimesCount() {
    return availableTimes_.size();
  }
  /**
   * <code>repeated int64 available_times = 2;</code>
   */
  public long getAvailableTimes(int index) {
    return availableTimes_.get(index);
  }
  private int availableTimesMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getResourceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceId_);
    }
    if (getAvailableTimesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(availableTimesMemoizedSerializedSize);
    }
    for (int i = 0; i < availableTimes_.size(); i++) {
      output.writeInt64NoTag(availableTimes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getResourceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < availableTimes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(availableTimes_.get(i));
      }
      size += dataSize;
      if (!getAvailableTimesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      availableTimesMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cv.scheduling.ResourceAvailabilityResponse)) {
      return super.equals(obj);
    }
    cv.scheduling.ResourceAvailabilityResponse other = (cv.scheduling.ResourceAvailabilityResponse) obj;

    boolean result = true;
    result = result && getResourceId()
        .equals(other.getResourceId());
    result = result && getAvailableTimesList()
        .equals(other.getAvailableTimesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getResourceId().hashCode();
    if (getAvailableTimesCount() > 0) {
      hash = (37 * hash) + AVAILABLE_TIMES_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableTimesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cv.scheduling.ResourceAvailabilityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cv.scheduling.ResourceAvailabilityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scheduling.ResourceAvailabilityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scheduling.ResourceAvailabilityResponse)
      cv.scheduling.ResourceAvailabilityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_ResourceAvailabilityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_ResourceAvailabilityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cv.scheduling.ResourceAvailabilityResponse.class, cv.scheduling.ResourceAvailabilityResponse.Builder.class);
    }

    // Construct using cv.scheduling.ResourceAvailabilityResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resourceId_ = "";

      availableTimes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_ResourceAvailabilityResponse_descriptor;
    }

    @java.lang.Override
    public cv.scheduling.ResourceAvailabilityResponse getDefaultInstanceForType() {
      return cv.scheduling.ResourceAvailabilityResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cv.scheduling.ResourceAvailabilityResponse build() {
      cv.scheduling.ResourceAvailabilityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cv.scheduling.ResourceAvailabilityResponse buildPartial() {
      cv.scheduling.ResourceAvailabilityResponse result = new cv.scheduling.ResourceAvailabilityResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.resourceId_ = resourceId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        availableTimes_ = java.util.Collections.unmodifiableList(availableTimes_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.availableTimes_ = availableTimes_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cv.scheduling.ResourceAvailabilityResponse) {
        return mergeFrom((cv.scheduling.ResourceAvailabilityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cv.scheduling.ResourceAvailabilityResponse other) {
      if (other == cv.scheduling.ResourceAvailabilityResponse.getDefaultInstance()) return this;
      if (!other.getResourceId().isEmpty()) {
        resourceId_ = other.resourceId_;
        onChanged();
      }
      if (!other.availableTimes_.isEmpty()) {
        if (availableTimes_.isEmpty()) {
          availableTimes_ = other.availableTimes_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureAvailableTimesIsMutable();
          availableTimes_.addAll(other.availableTimes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cv.scheduling.ResourceAvailabilityResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cv.scheduling.ResourceAvailabilityResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object resourceId_ = "";
    /**
     * <code>string resource_id = 1;</code>
     */
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resource_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resource_id = 1;</code>
     */
    public Builder setResourceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string resource_id = 1;</code>
     */
    public Builder clearResourceId() {
      
      resourceId_ = getDefaultInstance().getResourceId();
      onChanged();
      return this;
    }
    /**
     * <code>string resource_id = 1;</code>
     */
    public Builder setResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> availableTimes_ = java.util.Collections.emptyList();
    private void ensureAvailableTimesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        availableTimes_ = new java.util.ArrayList<java.lang.Long>(availableTimes_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getAvailableTimesList() {
      return java.util.Collections.unmodifiableList(availableTimes_);
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public int getAvailableTimesCount() {
      return availableTimes_.size();
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public long getAvailableTimes(int index) {
      return availableTimes_.get(index);
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public Builder setAvailableTimes(
        int index, long value) {
      ensureAvailableTimesIsMutable();
      availableTimes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public Builder addAvailableTimes(long value) {
      ensureAvailableTimesIsMutable();
      availableTimes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public Builder addAllAvailableTimes(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAvailableTimesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, availableTimes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 available_times = 2;</code>
     */
    public Builder clearAvailableTimes() {
      availableTimes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scheduling.ResourceAvailabilityResponse)
  }

  // @@protoc_insertion_point(class_scope:scheduling.ResourceAvailabilityResponse)
  private static final cv.scheduling.ResourceAvailabilityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cv.scheduling.ResourceAvailabilityResponse();
  }

  public static cv.scheduling.ResourceAvailabilityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceAvailabilityResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResourceAvailabilityResponse>() {
    @java.lang.Override
    public ResourceAvailabilityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceAvailabilityResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceAvailabilityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceAvailabilityResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cv.scheduling.ResourceAvailabilityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

