// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduling.proto

package cv.scheduling;

public interface ResourceAvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scheduling.ResourceAvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resource_id = 1;</code>
   */
  java.lang.String getResourceId();
  /**
   * <code>string resource_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getResourceIdBytes();

  /**
   * <code>repeated int64 available_times = 2;</code>
   */
  java.util.List<java.lang.Long> getAvailableTimesList();
  /**
   * <code>repeated int64 available_times = 2;</code>
   */
  int getAvailableTimesCount();
  /**
   * <code>repeated int64 available_times = 2;</code>
   */
  long getAvailableTimes(int index);
}
