// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduling.proto

package cv.scheduling;

/**
 * Protobuf type {@code scheduling.SchedulingRequest}
 */
public  final class SchedulingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scheduling.SchedulingRequest)
    SchedulingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SchedulingRequest.newBuilder() to construct.
  private SchedulingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SchedulingRequest() {
    courseId_ = "";
    teacherId_ = "";
    equipment_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    numStudents_ = 0;
    startTime_ = 0L;
    endTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SchedulingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            courseId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            teacherId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              equipment_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            equipment_.add(s);
            break;
          }
          case 32: {

            numStudents_ = input.readInt32();
            break;
          }
          case 40: {

            startTime_ = input.readInt64();
            break;
          }
          case 48: {

            endTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        equipment_ = equipment_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_SchedulingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_SchedulingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cv.scheduling.SchedulingRequest.class, cv.scheduling.SchedulingRequest.Builder.class);
  }

  private int bitField0_;
  public static final int COURSE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object courseId_;
  /**
   * <code>string course_id = 1;</code>
   */
  public java.lang.String getCourseId() {
    java.lang.Object ref = courseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      courseId_ = s;
      return s;
    }
  }
  /**
   * <code>string course_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCourseIdBytes() {
    java.lang.Object ref = courseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      courseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEACHER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object teacherId_;
  /**
   * <code>string teacher_id = 2;</code>
   */
  public java.lang.String getTeacherId() {
    java.lang.Object ref = teacherId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      teacherId_ = s;
      return s;
    }
  }
  /**
   * <code>string teacher_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTeacherIdBytes() {
    java.lang.Object ref = teacherId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      teacherId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EQUIPMENT_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList equipment_;
  /**
   * <code>repeated string equipment = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getEquipmentList() {
    return equipment_;
  }
  /**
   * <code>repeated string equipment = 3;</code>
   */
  public int getEquipmentCount() {
    return equipment_.size();
  }
  /**
   * <code>repeated string equipment = 3;</code>
   */
  public java.lang.String getEquipment(int index) {
    return equipment_.get(index);
  }
  /**
   * <code>repeated string equipment = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEquipmentBytes(int index) {
    return equipment_.getByteString(index);
  }

  public static final int NUM_STUDENTS_FIELD_NUMBER = 4;
  private int numStudents_;
  /**
   * <code>int32 num_students = 4;</code>
   */
  public int getNumStudents() {
    return numStudents_;
  }

  public static final int START_TIME_FIELD_NUMBER = 5;
  private long startTime_;
  /**
   * <code>int64 start_time = 5;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 6;
  private long endTime_;
  /**
   * <code>int64 end_time = 6;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCourseIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, courseId_);
    }
    if (!getTeacherIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teacherId_);
    }
    for (int i = 0; i < equipment_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, equipment_.getRaw(i));
    }
    if (numStudents_ != 0) {
      output.writeInt32(4, numStudents_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(5, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(6, endTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCourseIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, courseId_);
    }
    if (!getTeacherIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teacherId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < equipment_.size(); i++) {
        dataSize += computeStringSizeNoTag(equipment_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEquipmentList().size();
    }
    if (numStudents_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, numStudents_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, endTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cv.scheduling.SchedulingRequest)) {
      return super.equals(obj);
    }
    cv.scheduling.SchedulingRequest other = (cv.scheduling.SchedulingRequest) obj;

    boolean result = true;
    result = result && getCourseId()
        .equals(other.getCourseId());
    result = result && getTeacherId()
        .equals(other.getTeacherId());
    result = result && getEquipmentList()
        .equals(other.getEquipmentList());
    result = result && (getNumStudents()
        == other.getNumStudents());
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COURSE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCourseId().hashCode();
    hash = (37 * hash) + TEACHER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTeacherId().hashCode();
    if (getEquipmentCount() > 0) {
      hash = (37 * hash) + EQUIPMENT_FIELD_NUMBER;
      hash = (53 * hash) + getEquipmentList().hashCode();
    }
    hash = (37 * hash) + NUM_STUDENTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumStudents();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cv.scheduling.SchedulingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cv.scheduling.SchedulingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cv.scheduling.SchedulingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cv.scheduling.SchedulingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cv.scheduling.SchedulingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scheduling.SchedulingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scheduling.SchedulingRequest)
      cv.scheduling.SchedulingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_SchedulingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_SchedulingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cv.scheduling.SchedulingRequest.class, cv.scheduling.SchedulingRequest.Builder.class);
    }

    // Construct using cv.scheduling.SchedulingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      courseId_ = "";

      teacherId_ = "";

      equipment_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      numStudents_ = 0;

      startTime_ = 0L;

      endTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cv.scheduling.SchedulingServiceProto.internal_static_scheduling_SchedulingRequest_descriptor;
    }

    @java.lang.Override
    public cv.scheduling.SchedulingRequest getDefaultInstanceForType() {
      return cv.scheduling.SchedulingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public cv.scheduling.SchedulingRequest build() {
      cv.scheduling.SchedulingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cv.scheduling.SchedulingRequest buildPartial() {
      cv.scheduling.SchedulingRequest result = new cv.scheduling.SchedulingRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.courseId_ = courseId_;
      result.teacherId_ = teacherId_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        equipment_ = equipment_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.equipment_ = equipment_;
      result.numStudents_ = numStudents_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cv.scheduling.SchedulingRequest) {
        return mergeFrom((cv.scheduling.SchedulingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cv.scheduling.SchedulingRequest other) {
      if (other == cv.scheduling.SchedulingRequest.getDefaultInstance()) return this;
      if (!other.getCourseId().isEmpty()) {
        courseId_ = other.courseId_;
        onChanged();
      }
      if (!other.getTeacherId().isEmpty()) {
        teacherId_ = other.teacherId_;
        onChanged();
      }
      if (!other.equipment_.isEmpty()) {
        if (equipment_.isEmpty()) {
          equipment_ = other.equipment_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureEquipmentIsMutable();
          equipment_.addAll(other.equipment_);
        }
        onChanged();
      }
      if (other.getNumStudents() != 0) {
        setNumStudents(other.getNumStudents());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cv.scheduling.SchedulingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cv.scheduling.SchedulingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object courseId_ = "";
    /**
     * <code>string course_id = 1;</code>
     */
    public java.lang.String getCourseId() {
      java.lang.Object ref = courseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCourseIdBytes() {
      java.lang.Object ref = courseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public Builder setCourseId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      courseId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public Builder clearCourseId() {
      
      courseId_ = getDefaultInstance().getCourseId();
      onChanged();
      return this;
    }
    /**
     * <code>string course_id = 1;</code>
     */
    public Builder setCourseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      courseId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object teacherId_ = "";
    /**
     * <code>string teacher_id = 2;</code>
     */
    public java.lang.String getTeacherId() {
      java.lang.Object ref = teacherId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teacherId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string teacher_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeacherIdBytes() {
      java.lang.Object ref = teacherId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teacherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string teacher_id = 2;</code>
     */
    public Builder setTeacherId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      teacherId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string teacher_id = 2;</code>
     */
    public Builder clearTeacherId() {
      
      teacherId_ = getDefaultInstance().getTeacherId();
      onChanged();
      return this;
    }
    /**
     * <code>string teacher_id = 2;</code>
     */
    public Builder setTeacherIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      teacherId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList equipment_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEquipmentIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        equipment_ = new com.google.protobuf.LazyStringArrayList(equipment_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEquipmentList() {
      return equipment_.getUnmodifiableView();
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public int getEquipmentCount() {
      return equipment_.size();
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public java.lang.String getEquipment(int index) {
      return equipment_.get(index);
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEquipmentBytes(int index) {
      return equipment_.getByteString(index);
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public Builder setEquipment(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEquipmentIsMutable();
      equipment_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public Builder addEquipment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEquipmentIsMutable();
      equipment_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public Builder addAllEquipment(
        java.lang.Iterable<java.lang.String> values) {
      ensureEquipmentIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, equipment_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public Builder clearEquipment() {
      equipment_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipment = 3;</code>
     */
    public Builder addEquipmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEquipmentIsMutable();
      equipment_.add(value);
      onChanged();
      return this;
    }

    private int numStudents_ ;
    /**
     * <code>int32 num_students = 4;</code>
     */
    public int getNumStudents() {
      return numStudents_;
    }
    /**
     * <code>int32 num_students = 4;</code>
     */
    public Builder setNumStudents(int value) {
      
      numStudents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 num_students = 4;</code>
     */
    public Builder clearNumStudents() {
      
      numStudents_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 start_time = 5;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 start_time = 5;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_time = 5;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 end_time = 6;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 end_time = 6;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 end_time = 6;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scheduling.SchedulingRequest)
  }

  // @@protoc_insertion_point(class_scope:scheduling.SchedulingRequest)
  private static final cv.scheduling.SchedulingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cv.scheduling.SchedulingRequest();
  }

  public static cv.scheduling.SchedulingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SchedulingRequest>
      PARSER = new com.google.protobuf.AbstractParser<SchedulingRequest>() {
    @java.lang.Override
    public SchedulingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SchedulingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SchedulingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SchedulingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cv.scheduling.SchedulingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

