// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduling.proto

package cv.scheduling;

public final class SchedulingServiceProto {
  private SchedulingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_SchedulingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_SchedulingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_ResourceAvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_ResourceAvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_SchedulingResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_SchedulingResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020scheduling.proto\022\nscheduling\"\211\001\n\021Sched" +
      "ulingRequest\022\021\n\tcourse_id\030\001 \001(\t\022\022\n\nteach" +
      "er_id\030\002 \001(\t\022\021\n\tequipment\030\003 \003(\t\022\024\n\014num_st" +
      "udents\030\004 \001(\005\022\022\n\nstart_time\030\005 \001(\003\022\020\n\010end_" +
      "time\030\006 \001(\003\"L\n\034ResourceAvailabilityRespon" +
      "se\022\023\n\013resource_id\030\001 \001(\t\022\027\n\017available_tim" +
      "es\030\002 \003(\003\"<\n\030SchedulingResultResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\242\002\n\021Sched" +
      "ulingService\022Q\n\010Schedule\022\035.scheduling.Sc" +
      "hedulingRequest\032$.scheduling.SchedulingR" +
      "esultResponse\"\000\022`\n\021CheckAvailability\022\035.s" +
      "cheduling.SchedulingRequest\032(.scheduling" +
      ".ResourceAvailabilityResponse\"\0000\001\022X\n\rBat" +
      "chSchedule\022\035.scheduling.SchedulingReques" +
      "t\032$.scheduling.SchedulingResultResponse\"" +
      "\000(\001B)\n\rcv.schedulingB\026SchedulingServiceP" +
      "rotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_scheduling_SchedulingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scheduling_SchedulingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_SchedulingRequest_descriptor,
        new java.lang.String[] { "CourseId", "TeacherId", "Equipment", "NumStudents", "StartTime", "EndTime", });
    internal_static_scheduling_ResourceAvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scheduling_ResourceAvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_ResourceAvailabilityResponse_descriptor,
        new java.lang.String[] { "ResourceId", "AvailableTimes", });
    internal_static_scheduling_SchedulingResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_scheduling_SchedulingResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_SchedulingResultResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
