// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package edu.studentScheduling;

public interface AddStudentScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scheduling.AddStudentScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>repeated string course_ids = 2;</code>
   */
  java.util.List<java.lang.String>
      getCourseIdsList();
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  int getCourseIdsCount();
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  java.lang.String getCourseIds(int index);
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdsBytes(int index);
}
