// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package edu.studentScheduling;

public interface GetStudentScheduleByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scheduling.GetStudentScheduleByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();
}
