// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package edu.studentScheduling;

/**
 * Protobuf type {@code scheduling.GetStudentScheduleByIdResponse}
 */
public  final class GetStudentScheduleByIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scheduling.GetStudentScheduleByIdResponse)
    GetStudentScheduleByIdResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetStudentScheduleByIdResponse.newBuilder() to construct.
  private GetStudentScheduleByIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetStudentScheduleByIdResponse() {
    studentId_ = "";
    courseIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetStudentScheduleByIdResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            studentId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              courseIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            courseIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        courseIds_ = courseIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.studentScheduling.StudentSchedulingServiceImpl.internal_static_scheduling_GetStudentScheduleByIdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.studentScheduling.StudentSchedulingServiceImpl.internal_static_scheduling_GetStudentScheduleByIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.studentScheduling.GetStudentScheduleByIdResponse.class, edu.studentScheduling.GetStudentScheduleByIdResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STUDENT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object studentId_;
  /**
   * <code>string student_id = 1;</code>
   */
  public java.lang.String getStudentId() {
    java.lang.Object ref = studentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentId_ = s;
      return s;
    }
  }
  /**
   * <code>string student_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStudentIdBytes() {
    java.lang.Object ref = studentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COURSE_IDS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList courseIds_;
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCourseIdsList() {
    return courseIds_;
  }
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  public int getCourseIdsCount() {
    return courseIds_.size();
  }
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  public java.lang.String getCourseIds(int index) {
    return courseIds_.get(index);
  }
  /**
   * <code>repeated string course_ids = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCourseIdsBytes(int index) {
    return courseIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStudentIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentId_);
    }
    for (int i = 0; i < courseIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, courseIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStudentIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < courseIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(courseIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCourseIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.studentScheduling.GetStudentScheduleByIdResponse)) {
      return super.equals(obj);
    }
    edu.studentScheduling.GetStudentScheduleByIdResponse other = (edu.studentScheduling.GetStudentScheduleByIdResponse) obj;

    boolean result = true;
    result = result && getStudentId()
        .equals(other.getStudentId());
    result = result && getCourseIdsList()
        .equals(other.getCourseIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STUDENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStudentId().hashCode();
    if (getCourseIdsCount() > 0) {
      hash = (37 * hash) + COURSE_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getCourseIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.studentScheduling.GetStudentScheduleByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.studentScheduling.GetStudentScheduleByIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scheduling.GetStudentScheduleByIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scheduling.GetStudentScheduleByIdResponse)
      edu.studentScheduling.GetStudentScheduleByIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.studentScheduling.StudentSchedulingServiceImpl.internal_static_scheduling_GetStudentScheduleByIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.studentScheduling.StudentSchedulingServiceImpl.internal_static_scheduling_GetStudentScheduleByIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.studentScheduling.GetStudentScheduleByIdResponse.class, edu.studentScheduling.GetStudentScheduleByIdResponse.Builder.class);
    }

    // Construct using edu.studentScheduling.GetStudentScheduleByIdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      studentId_ = "";

      courseIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.studentScheduling.StudentSchedulingServiceImpl.internal_static_scheduling_GetStudentScheduleByIdResponse_descriptor;
    }

    @java.lang.Override
    public edu.studentScheduling.GetStudentScheduleByIdResponse getDefaultInstanceForType() {
      return edu.studentScheduling.GetStudentScheduleByIdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public edu.studentScheduling.GetStudentScheduleByIdResponse build() {
      edu.studentScheduling.GetStudentScheduleByIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.studentScheduling.GetStudentScheduleByIdResponse buildPartial() {
      edu.studentScheduling.GetStudentScheduleByIdResponse result = new edu.studentScheduling.GetStudentScheduleByIdResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.studentId_ = studentId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        courseIds_ = courseIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.courseIds_ = courseIds_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.studentScheduling.GetStudentScheduleByIdResponse) {
        return mergeFrom((edu.studentScheduling.GetStudentScheduleByIdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.studentScheduling.GetStudentScheduleByIdResponse other) {
      if (other == edu.studentScheduling.GetStudentScheduleByIdResponse.getDefaultInstance()) return this;
      if (!other.getStudentId().isEmpty()) {
        studentId_ = other.studentId_;
        onChanged();
      }
      if (!other.courseIds_.isEmpty()) {
        if (courseIds_.isEmpty()) {
          courseIds_ = other.courseIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCourseIdsIsMutable();
          courseIds_.addAll(other.courseIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.studentScheduling.GetStudentScheduleByIdResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.studentScheduling.GetStudentScheduleByIdResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object studentId_ = "";
    /**
     * <code>string student_id = 1;</code>
     */
    public java.lang.String getStudentId() {
      java.lang.Object ref = studentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string student_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStudentIdBytes() {
      java.lang.Object ref = studentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string student_id = 1;</code>
     */
    public Builder setStudentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string student_id = 1;</code>
     */
    public Builder clearStudentId() {
      
      studentId_ = getDefaultInstance().getStudentId();
      onChanged();
      return this;
    }
    /**
     * <code>string student_id = 1;</code>
     */
    public Builder setStudentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList courseIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCourseIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        courseIds_ = new com.google.protobuf.LazyStringArrayList(courseIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCourseIdsList() {
      return courseIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public int getCourseIdsCount() {
      return courseIds_.size();
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public java.lang.String getCourseIds(int index) {
      return courseIds_.get(index);
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCourseIdsBytes(int index) {
      return courseIds_.getByteString(index);
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public Builder setCourseIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseIdsIsMutable();
      courseIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public Builder addCourseIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseIdsIsMutable();
      courseIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public Builder addAllCourseIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureCourseIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, courseIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public Builder clearCourseIds() {
      courseIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string course_ids = 2;</code>
     */
    public Builder addCourseIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCourseIdsIsMutable();
      courseIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scheduling.GetStudentScheduleByIdResponse)
  }

  // @@protoc_insertion_point(class_scope:scheduling.GetStudentScheduleByIdResponse)
  private static final edu.studentScheduling.GetStudentScheduleByIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.studentScheduling.GetStudentScheduleByIdResponse();
  }

  public static edu.studentScheduling.GetStudentScheduleByIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStudentScheduleByIdResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetStudentScheduleByIdResponse>() {
    @java.lang.Override
    public GetStudentScheduleByIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetStudentScheduleByIdResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetStudentScheduleByIdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStudentScheduleByIdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.studentScheduling.GetStudentScheduleByIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

