// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package edu.studentScheduling;

public final class StudentSchedulingServiceImpl {
  private StudentSchedulingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_AddStudentScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_AddStudentScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_AddStudentScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_AddStudentScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_GetStudentScheduleByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_GetStudentScheduleByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_GetStudentScheduleByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_GetStudentScheduleByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_UpdateStudentScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_UpdateStudentScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduling_UpdateStudentScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduling_UpdateStudentScheduleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\nscheduling\"C\n\031AddStuden" +
      "tScheduleRequest\022\022\n\nstudent_id\030\001 \001(\t\022\022\n\n" +
      "course_ids\030\002 \003(\t\"=\n\032AddStudentScheduleRe" +
      "sponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"" +
      "3\n\035GetStudentScheduleByIdRequest\022\022\n\nstud" +
      "ent_id\030\001 \001(\t\"H\n\036GetStudentScheduleByIdRe" +
      "sponse\022\022\n\nstudent_id\030\001 \001(\t\022\022\n\ncourse_ids" +
      "\030\002 \003(\t\"F\n\034UpdateStudentScheduleRequest\022\022" +
      "\n\nstudent_id\030\001 \001(\t\022\022\n\ncourse_ids\030\002 \003(\t\"@" +
      "\n\035UpdateStudentScheduleResponse\022\016\n\006statu" +
      "s\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2\332\002\n\021StudentMana" +
      "gement\022c\n\022AddStudentSchedule\022%.schedulin" +
      "g.AddStudentScheduleRequest\032&.scheduling" +
      ".AddStudentScheduleResponse\022o\n\026GetStuden" +
      "tScheduleById\022).scheduling.GetStudentSch" +
      "eduleByIdRequest\032*.scheduling.GetStudent" +
      "ScheduleByIdResponse\022o\n\026UpdateStudentSch" +
      "edules\022(.scheduling.UpdateStudentSchedul" +
      "eRequest\032).scheduling.UpdateStudentSched" +
      "uleResponse(\001B7\n\025edu.studentSchedulingB\034" +
      "StudentSchedulingServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_scheduling_AddStudentScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scheduling_AddStudentScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_AddStudentScheduleRequest_descriptor,
        new java.lang.String[] { "StudentId", "CourseIds", });
    internal_static_scheduling_AddStudentScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scheduling_AddStudentScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_AddStudentScheduleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_scheduling_GetStudentScheduleByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_scheduling_GetStudentScheduleByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_GetStudentScheduleByIdRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_scheduling_GetStudentScheduleByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_scheduling_GetStudentScheduleByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_GetStudentScheduleByIdResponse_descriptor,
        new java.lang.String[] { "StudentId", "CourseIds", });
    internal_static_scheduling_UpdateStudentScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_scheduling_UpdateStudentScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_UpdateStudentScheduleRequest_descriptor,
        new java.lang.String[] { "StudentId", "CourseIds", });
    internal_static_scheduling_UpdateStudentScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_scheduling_UpdateStudentScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduling_UpdateStudentScheduleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
