// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package edu.studentScheduling;

public interface UpdateStudentScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scheduling.UpdateStudentScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
